ARG LAGOON_PROJECT
ARG LAGOON_ENVIRONMENT
ARG BUILD_HASH=latest

ARG RASCH_PROJECT
ARG LAGOON_GIT_BRANCH
ARG LAGOON_GIT_SHA
ARG LAGOON_BUILD_TYPE
ARG LAGOON_PR_TITLE
ARG LAGOON_PR_BASE_BRANCH
ARG LAGOON_PR_HEAD_BRANCH
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY

FROM harbor.rasch3.amazee.io/${LAGOON_PROJECT}/${LAGOON_ENVIRONMENT}/node:${BUILD_HASH}

CMD ["node","scripts/ignition.js","--start"]
