FROM amazeeio/node:22-builder-24.12.0 as builder

# Use changes to package.json and yarn.lock to see if Docker should use cached nodejs deps
COPY package.json yarn.lock .yarnrc.yml /app/
COPY .yarn /app/.yarn

# debug info for node version
RUN node -v
RUN yarn -v

# Install Python, pip, and setuptools (Alpine Linux)
RUN apk update && \
    apk add --no-cache python3 py3-pip py3-setuptools

# run yarn install and remove the .yarn-cache as we don't need that on our image
RUN yarn set version 3.2.1
RUN yarn install

# Now copy in our application code.
COPY . /app