FROM amazeeio/node:22-builder-24.12.0 as builder

# Use changes to package.json and yarn.lock to see if Docker should use cached nodejs deps
COPY package.json yarn.lock .yarnrc.yml /app/
COPY .yarn /app/.yarn

# debug info for node version
RUN node -v
RUN yarn -v

# Install Python, pip, and setuptools (Alpine Linux)
RUN apk update && \
    apk add --no-cache python3 py3-pip py3-setuptools

RUN yarn set version 3.2.1
RUN yarn install

# Now copy in our application code.
COPY . /app

ENV NODE_ENV production

# Due to issue with not injected manifest.json file to HTML markup the plugin "speed-measure-webpack-plugin" is disabled here
ENV DISABLE_WEBPACK_MEASURE true

# All these ARGs are used by setup-env.sh
ARG RASCH_PROJECT
ARG LAGOON_GIT_BRANCH
ARG LAGOON_BUILD_TYPE
ARG LAGOON_PR_TITLE
ARG LAGOON_PR_BASE_BRANCH
ARG LAGOON_PR_HEAD_BRANCH
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY

# setup-env.sh needs bash
RUN apk add --no-cache bash curl

# This configures the environment variables based on the project, build type an branch into the main root
RUN ./.lagoon/setup-env.sh

# Prefixed with `/lagoon/entrypoints.sh` so we get the env variables sourced we need
RUN /lagoon/entrypoints.sh yarn run build \
    # Remove all node_modules and re-install just the important ones for SSR
    && rm -rf node_modules coverage src package.json .vscode certs cicd docs load-testing locust logs todos \
    && yarn add full-icu@1.3.4 inquirer@8.0.0 dotenv@8.2.0 \
    && yarn cache clean

FROM amazeeio/node:22

ENV NODE_ENV production

# Copy from the builder
COPY --from=builder /app /app

# All these ARGs are passed at build time
ARG BUILD_TAGGED_AS_RELEASE="FALSE"
# This env var can be used downstream by post-deploy steps
ENV BUILD_TAGGED_AS_RELEASE=$BUILD_TAGGED_AS_RELEASE

# CMD ["yarn", "run", "start"]
CMD ["node","scripts/ignition.js","--start"];
