export const trainings: Options = [
  'Anlehre',
  'Berufslehre',
  'KV Lehre/HS/keine Angabe',
  'Fachausbildung',
  'Höhere Fachschule',
  'Uni-/Hochschulabschluss',
  'MAS-Lehrg',
  'Fachhochschulabschluss',
];

export const careers: Options = [
  'Berufseinsteiger',
  'mit Berufserfahrung',
  'Spezialist',
  'Führungskraft/Direktor/Geschäftsführer',
];

export const leadingExperiences: Options = [
  'keine Führungsverantwortung',
  '1-5',
  '6-10',
  '11-20',
  '21-50',
  '51-100',
  '101 und mehr',
];

export const experienceYears: Options = [
  'weniger als 2 Jahre',
  '2 bis 4 Jahre',
  '5 bis 10 Jahre',
  'über 10 Jahre',
];

export const jobCategories: Options = [
  'Architektur',
  'Bau',
  'Finanzen',
  'Gastgewerbe',
  'Hotel',
  'Gesundheit und Pflege',
  'Gewerbe und Industrie',
  'Informatik',
  'Kaufmännische Berufe',
  'Marketing',
  'Soziales',
  'technische Industrie',
  'Verkauf',
  'Diverses',
];

export const jobs: Options = [
  'Analyst',
  'Angestellter',
  'Anlageberater',
  'Anwalt',
  'Apotheker',
  'Arbeitsplaner_AVOR',
  'Archivar',
  'Arzt',
  'Arztsekretär',
  'Assistent',
  'Augenoptiker',
  'Ausbildner',
  'Aussendienst',
  'Autolackierer',
  'Automatiker',
  'Automechaniker',
  'Automonteur',
  'Bankangestellter',
  'Bauingenieur',
  'Bauleiter',
  'Betriebsfachmann',
  'Betriebsleiter',
  'Betriebsökonom',
  'Betriebstechniker',
  'Betriebswirt',
  'Biolog',
  'Bodenleger',
  'Buchbinder',
  'Buchhändler',
  'Buchhalter',
  'Büroangestellter',
  'Callcenter-Agent',
  'CFO',
  'Chauffeur',
  'Chemielaborant',
  'Chemiker',
  'Coiffeur',
  'Controller',
  'Dachdecker',
  'Datenbankadministrator',
  'Dentalassistent',
  'Detailhandelsangestellter',
  'Direktionsasisstent',
  'Disponent',
  'Drogist',
  'Drucker',
  'Einkäufer',
  'Elektroingenieur',
  'Elektroinstallateur',
  'Elektrokontrolleur',
  'Elektromechaniker',
  'Elektroniker',
  'Elektroplaner',
  'Elektrotechniker',
  'Empfangsangestellter',
  'Feinmechaniker',
  'Finanzberater',
  'Forstwart',
  'Gärtner',
  'Gipser',
  'Grafiker',
  'Hauswart',
  'Heimleiter',
  'Heizungsmonteur',
  'Hilfsarbeiter',
  'Hotelier',
  'Immobilienverwalter',
  'Informatik-Berater',
  'Informatik-Projektleiter',
  'Informatik-Supporter',
  'Informatiker',
  'Ingenieur',
  'Journalist',
  'Jurist',
  'Kaufmann',
  'Kellner',
  'Kleinkinderzieher',
  'Koch',
  'Konditor',
  'Konstrukteur',
  'Krankenpfleger',
  'Küchenchef',
  'Kundenberater',
  'Kunststofftechnolog',
  'Laborant',
  'Lagerist',
  'Landschaftsgärtner',
  'Lehrer',
  'Lehrling',
  'Logistikassistent',
  'Logistiker',
  'Lokführer',
  'Magaziner',
  'Maler',
  'Marketingassistent',
  'Marketingleiter',
  'Marketingplaner',
  'Maschineningenieur',
  'Maschinenmechaniker',
  'Maurer',
  'Mechaniker',
  'Mediamatiker',
  'Medizinischer-Praxisassistent',
  'Metallbauer',
  'Metallbauschlosser',
  'Metzger',
  'Monteur',
  'Operator',
  'Organisator',
  'Personalassistent',
  'Personalberater',
  'Personalfachmann',
  'Personalleiter',
  'Pflegeassistent',
  'Pflegefachmann',
  'Pharma-Assistent',
  'Physiker',
  'Physiotherapeut',
  'Pilot',
  'Plattenleger',
  'Polier',
  'Polizist',
  'Polygraf',
  'Polymechaniker',
  'Postangestellter',
  'PR-Berater',
  'Praktikant',
  'Produktionsleiter',
  'Produktmanager',
  'Projektleiter',
  'Psychologe',
  'Redaktor',
  'Reiseberater',
  'Revisor',
  'Sachbearbeiter',
  'Sanitär',
  'Schlosser',
  'Schreiner',
  'Sekretär',
  'Servicefachangestellter',
  'Servicetechniker',
  'Softwareentwickler',
  'Sozialarbeiter',
  'Sozialpädagoge',
  'Spengler',
  'Student',
  'System-Engineer',
  'Systemadministrator',
  'Techniker',
  'Technischer-Kaufmann',
  'Telefonist',
  'Telematiker',
  'Treuhänder',
  'Übersetzer',
  'Underwriter',
  'Unternehmensberater',
  'Verkäufer',
  'Verkaufsberater',
  'Verkaufsingenieur',
  'Verkaufskoordinator',
  'Verkaufsleiter',
  'Versicherungsberater',
  'Verwalter',
  'Verwaltungsangestellter',
  'Webdesigner',
  'Webmaster',
  'Webpublisher',
  'Werbeberater',
  'Werkzeugmacher',
  'Wirtschaftsinformatiker',
  'Wirtschaftsprüfer',
  'Zahnarzt',
  'Zahntechniker',
  'Zimmermann',
  'Andere',
  'keine Angabe',
];

export const companyEmployees: Options = [
  'Einzelfirma',
  '1-10 Mitarbeiter',
  '11-50 Mitarbeiter',
  '51-200 Mitarbeiter',
  '201-500 Mitarbeiter',
  '501-1000 Mitarbeiter',
  '1001-5000 Mitarbeiter',
  '5001-10000 Mitarbeiter',
  '10001 und mehr Mitarbeiter',
];

export const branches: Options = [
  'Autogewerbe',
  'Banken',
  'Bau',
  'Beratung/Revision',
  'Bund',
  'Chemie',
  'Detailhandel',
  'Druck und Grafik',
  'Elektroindustrie',
  'Gastronomie und Tourismus',
  'Gesundheitswesen',
  'Informatik',
  'Kantone/Gemeinden',
  'Maschinen und Metallindustrie',
  'Medizinaltechnik',
  'Militär',
  'Nahrungsmittel',
  'Pharma',
  'Telecom',
  'Textil',
  'Uhren/Feintechnik',
  'Unterrichtswesen',
  'Verkehrsbetriebe',
  'Versicherungen',
  'Andere',
  'keine Angabe',
];

export const companySorts: Options = [
  'Einzelunternehmen',
  'Genossenschaft',
  'Kollektivgesellschaft',
  'Gemeinnützig',
  'GmbH',
  'AG',
  'Staatlich',
];

export const genders: Options = ['Mann', 'Frau'];

export const countries: Options = [
  'Ägypten',
  'Albanien',
  'Angola',
  'Argentinien',
  'Armenien',
  'Aserbaidschan',
  'Äthiopien',
  'Australien',
  'Bangladesch',
  'Belarus',
  'Belgien',
  'Belize',
  'Benin',
  'Bosnien',
  'Brasilien',
  'Bulgarien',
  'China',
  "Côte d'Ivoire",
  'Dänemark',
  'Deutschland',
  'Dominikanische Repub',
  'Ecuador',
  'Ehemaliges Jugoslawien',
  'Eritrea',
  'Estland',
  'Finnland',
  'Frankreich',
  'Griechenland',
  'Indien',
  'Indonesien',
  'Irak',
  'Iran',
  'Irland',
  'Israel',
  'Italien',
  'Kamerun',
  'Kasachstan',
  'Kenia',
  'Kolumbien',
  'Kroatien',
  'Kuba',
  'Laos',
  'Lettland',
  'Liechtenstein',
  'Litauen',
  'Mongolei',
  'Montenegro',
  'Niederlande',
  'Nigeria',
  'Österreich',
  'Pakistan',
  'Peru',
  'Philippinen',
  'Polen',
  'Portugal',
  'Rumänien',
  'Russland',
  'Schweden',
  'Schweiz',
  'Serbien',
  'Singapur',
  'Slowakei',
  'Slowenien',
  'Spanien',
  'Sri Lanka',
  'Thailand',
  'Trinidad und Tobago',
  'Tschechische Republik',
  'Tunesien',
  'Türkei',
  'Ukraine',
  'Ungarn',
  'Uruguay',
  'Usbekistan',
  'Vereinigte Staaten',
  'Vereinigtes Königreich',
  'Vietnam',
  'Keine Angabe',
];

export const TRAINING_SELECT_ID = 'ab';
export const WORKLOAD_SELECT_ID = 'Pensum';
export const BIRTH_YEAR_SELECT_ID = 'Alter';
export const CAREER_SELECT_ID = 'kl';
export const LEADING_DURATION_SELECT_ID = 'Lead';
export const FUNCTION_DURATION_SELECT_ID = 'Dalter';
export const DOMAIN_DURATION_SELECT_ID = 'Balter';
export const JOB_CATEGORY_SELECT_ID = 'Rubrik';
export const JOB_SELECT_ID = 'Beruf';
export const COMPANY_EMPLOYEES_SELECT_ID = 'Firmengroesse';
export const COMPANY_SIZE_SELECT_ID = 'Geogr';
export const WORKPLACE_SELECT_ID = 'Kanton';
export const DOMAIN_SELECT_ID = 'Branche';
export const COMPANY_SORT_SELECT_ID = 'Gesellschaft';
export const NATIONALITY_SELECT_ID = 'Land';
export const GENDER_SELECT_ID = 'Geschlecht';
export const AGREEMENTS_CHECKBOX_ID = 'agb';
export const NEWSLETTER_CHECKBOX_ID = 'newsletter';
export const EMAIL_INPUT_ID = 'Email';
export const TRAINING_DESIGNATION_INPUT_ID = 'g_ausbildung';
export const SCHOOL_INPUT_ID = 'g_schule';
