import { fbAppId } from '../../../../shared/helpers/metaData';
import {
  SVG_ICONS_TYPE_BEO_BOOKMARK_ACTIVE,
  SVG_ICONS_TYPE_BEO_BOOKMARK_INACTIVE,
  SVG_ICONS_TYPE_BEO_COMMENT,
  SVG_ICONS_TYPE_BEO_GIFT,
  SVG_ICONS_TYPE_BEO_PLAY,
  SVG_ICONS_TYPE_BEO_PRINT,
  SVG_ICONS_TYPE_BEO_SHARE,
  SVG_ICONS_TYPE_FACEBOOK,
  SVG_ICONS_TYPE_LINKEDIN,
  SVG_ICONS_TYPE_MAIL,
  SVG_ICONS_TYPE_MESSENGER,
  SVG_ICONS_TYPE_PINTEREST,
  SVG_ICONS_TYPE_TWITTER,
  SVG_ICONS_TYPE_WHATSAPP,
  SVG_ICONS_TYPE_XING,
} from '../../../../../shared/constants/svgIcons';
import {
  UTILITY_BAR_BEYOND_WORDS_LABEL,
  UTILITY_BAR_BOOKMARKS_ACTIVE_LABEL,
  UTILITY_BAR_BOOKMARKS_INACTIVE_LABEL,
  UTILITY_BAR_COMMENTS_LABEL,
  UTILITY_BAR_EMAIL_LABEL,
  UTILITY_BAR_FACEBOOK_LABEL,
  UTILITY_BAR_GIFT,
  UTILITY_BAR_LINKEDIN_LABEL,
  UTILITY_BAR_MESSENGER_LABEL,
  UTILITY_BAR_PINTEREST_LABEL,
  UTILITY_BAR_PRINT_LABEL,
  UTILITY_BAR_SHARE_LABEL,
  UTILITY_BAR_TWITTER_LABEL,
  UTILITY_BAR_WHATSAPP_LABEL,
  UTILITY_BAR_XING_LABEL,
  UTILITY_TYPE_BEYOND_WORDS,
  UTILITY_TYPE_BOOKMARKS,
  UTILITY_TYPE_COMMENTS,
  UTILITY_TYPE_EMAIL,
  UTILITY_TYPE_FACEBOOK,
  UTILITY_TYPE_GIFT,
  UTILITY_TYPE_GOOGLE_NEWS,
  UTILITY_TYPE_LINKEDIN,
  UTILITY_TYPE_MESSENGER,
  UTILITY_TYPE_PINTEREST,
  UTILITY_TYPE_PRINT,
  UTILITY_TYPE_SHARE,
  UTILITY_TYPE_TWITTER,
  UTILITY_TYPE_WHATSAPP,
  UTILITY_TYPE_XING,
} from '../../../../../shared/constants/utilitybar';
import grid from '../../../../../common/assets/styles/grid.legacy.css';
import { UtilityItemProps } from '../../../../../common/components/UtilityBar/typings';

export {
  UTILITY_TYPE_WHATSAPP,
  UTILITY_TYPE_FACEBOOK,
  UTILITY_TYPE_TWITTER,
  UTILITY_TYPE_EMAIL,
  UTILITY_TYPE_PRINT,
  UTILITY_TYPE_SHARE,
  UTILITY_TYPE_COMMENTS,
  UTILITY_TYPE_MESSENGER,
  UTILITY_TYPE_LINKEDIN,
  UTILITY_TYPE_XING,
  UTILITY_TYPE_PINTEREST,
  UTILITY_TYPE_BOOKMARKS,
  UTILITY_TYPE_GOOGLE_NEWS,
  UTILITY_BAR_WHATSAPP_LABEL,
  UTILITY_BAR_FACEBOOK_LABEL,
  UTILITY_BAR_MESSENGER_LABEL,
  UTILITY_BAR_LINKEDIN_LABEL,
  UTILITY_BAR_XING_LABEL,
  UTILITY_BAR_PINTEREST_LABEL,
  UTILITY_BAR_TWITTER_LABEL,
  UTILITY_BAR_EMAIL_LABEL,
  UTILITY_BAR_PRINT_LABEL,
  UTILITY_BAR_SHARE_LABEL,
  UTILITY_BAR_COMMENTS_LABEL,
  UTILITY_BAR_BOOKMARKS_INACTIVE_LABEL,
  UTILITY_BAR_BOOKMARKS_ACTIVE_LABEL,
};

export const AVAILABLE_UTILITIES: Array<UtilityItemProps> = [
  {
    id: UTILITY_TYPE_WHATSAPP,
    iconLabel: UTILITY_BAR_WHATSAPP_LABEL,
    iconType: SVG_ICONS_TYPE_WHATSAPP,
    targetType: '_blank',
    url: 'whatsapp://send?text=[field_short_title]:[field_title] | Beobachter | [url]',
    referrer: `utm_source=${UTILITY_TYPE_WHATSAPP.toLowerCase()}&utm_medium=social&utm_campaign=share-button`,
    addClass: grid.HiddenSmUp,
  },
  {
    id: UTILITY_TYPE_FACEBOOK,
    iconLabel: UTILITY_BAR_FACEBOOK_LABEL,
    iconType: SVG_ICONS_TYPE_FACEBOOK,
    url: 'https://www.facebook.com/sharer/sharer.php?u=[url]',
    referrer: `utm_source=facebook&utm_medium=social&utm_campaign=share-button`,
    targetType: '_blank',
  },
  {
    id: UTILITY_TYPE_TWITTER,
    iconLabel: UTILITY_BAR_TWITTER_LABEL,
    iconType: SVG_ICONS_TYPE_TWITTER,
    url:
      'https://twitter.com/share?url=[url]' +
      '&text=[field_social_media_title]&via=BeobachterRat',
    referrer: `utm_source=twitter&utm_medium=social&utm_campaign=share-button`,
    targetType: '_blank',
  },
  {
    id: UTILITY_TYPE_EMAIL,
    iconLabel: UTILITY_BAR_EMAIL_LABEL,
    iconType: SVG_ICONS_TYPE_MAIL,
    url:
      'mailto:?subject=Empfohlener%20Artikel%20von%20beobachter.ch&body=Guten%20Tag%2C%0A%0AIhnen%20' +
      'wurde%20dieser%20Artikel%20von%20beobachter.ch%20empfohlen%3A%0A%0A[url] - [field_short_title]',
    referrer: `utm_source=mail&utm_medium=social&utm_campaign=share-button`,
    targetType: '_blank',
  },
  {
    id: UTILITY_TYPE_PRINT,
    iconLabel: UTILITY_BAR_PRINT_LABEL,
    iconType: SVG_ICONS_TYPE_BEO_PRINT,
    url: '',
    targetType: '_blank',
    onClick: () => print(),
    addClass: grid.HiddenSmDown,
  },
  {
    id: UTILITY_TYPE_SHARE,
    iconLabel: UTILITY_BAR_SHARE_LABEL,
    iconType: SVG_ICONS_TYPE_BEO_SHARE,
    url: '',
  },
  {
    id: UTILITY_TYPE_COMMENTS,
    iconLabel: UTILITY_BAR_COMMENTS_LABEL,
    iconType: SVG_ICONS_TYPE_BEO_COMMENT,
    url: '#comments',
  },
  {
    id: UTILITY_TYPE_MESSENGER,
    iconLabel: UTILITY_BAR_MESSENGER_LABEL,
    iconType: SVG_ICONS_TYPE_MESSENGER,
    url: `https://www.facebook.com/dialog/send?app_id=${fbAppId}&link=[url]&redirect_uri=[url]`,
    referrer: `utm_source=messenger&utm_medium=social&utm_campaign=share-button`,
    targetType: '_blank',
  },
  {
    id: UTILITY_TYPE_LINKEDIN,
    iconLabel: UTILITY_BAR_LINKEDIN_LABEL,
    iconType: SVG_ICONS_TYPE_LINKEDIN,
    url: 'http://www.linkedin.com/shareArticle?url=[url]&title=[field_short_title]&summary=[field_lead]',
    referrer: `utm_source=linkedin&utm_medium=social&utm_campaign=share-button`,
    targetType: '_blank',
  },
  {
    id: UTILITY_TYPE_XING,
    iconLabel: UTILITY_BAR_XING_LABEL,
    iconType: SVG_ICONS_TYPE_XING,
    url: 'https://www.xing.com/spi/shares/new?url=[url]',
    referrer: `utm_source=xing&utm_medium=social&utm_campaign=share-button`,
    targetType: '_blank',
  },
  {
    id: UTILITY_TYPE_PINTEREST,
    iconLabel: UTILITY_BAR_PINTEREST_LABEL,
    iconType: SVG_ICONS_TYPE_PINTEREST,
    url: 'https://www.pinterest.ch/pin/create/button/?description=[field_lead]&media=[field_og_image]&url=[url]',
    referrer: `utm_source=pinterest&utm_medium=social&utm_campaign=share-button`,
    targetType: '_blank',
  },
  /*
   * UtilityBookmarkLink component which works when id === UTILITY_TYPE_BOOKMARKS doesn't use url,
   * and the UtilityLink doesn't use iconInactiveLabel and iconInactiveType.
   * It should be refactored while adding component support to UtilityBar
   */
  {
    id: UTILITY_TYPE_BOOKMARKS,
    iconLabel: UTILITY_BAR_BOOKMARKS_ACTIVE_LABEL,
    iconInactiveLabel: UTILITY_BAR_BOOKMARKS_INACTIVE_LABEL,
    iconType: SVG_ICONS_TYPE_BEO_BOOKMARK_ACTIVE,
    iconInactiveType: SVG_ICONS_TYPE_BEO_BOOKMARK_INACTIVE,
    url: '',
    targetType: '_blank',
  },
  {
    id: UTILITY_TYPE_BEYOND_WORDS,
    iconLabel: UTILITY_BAR_BEYOND_WORDS_LABEL,
    iconType: SVG_ICONS_TYPE_BEO_PLAY,
    url: '',
  },
  {
    id: UTILITY_TYPE_GIFT,
    iconLabel: UTILITY_BAR_GIFT,
    iconType: SVG_ICONS_TYPE_BEO_GIFT,
    url: '',
  },
];
