const path = require('path');
const app = process.env.APP || '';

module.exports = {
  'form.legacy.css': path.resolve(
    process.cwd(),
    'src',
    app,
    'screens',
    'App',
    'assets',
    'styles',
    'form.legacy.css',
  ),
  'grid.legacy.css': path.resolve(
    process.cwd(),
    'src',
    app,
    'screens',
    'App',
    'assets',
    'styles',
    'grid.legacy.css',
  ),
  '@grid.legacy.css': path.resolve(
    process.cwd(),
    'src',
    'common',
    'assets',
    'styles',
    'grid.legacy.css',
  ),
  '@variablesDefault.legacy.css': path.resolve(
    process.cwd(),
    'src',
    'common',
    'assets',
    'styles',
    'variablesDefault.legacy.css',
  ),
  'helpers.legacy.css': path.resolve(
    process.cwd(),
    'src',
    app,
    'screens',
    'App',
    'assets',
    'styles',
    'helpers.legacy.css',
  ),
  'raschFont.legacy.css': path.resolve(
    process.cwd(),
    'src',
    app,
    'screens',
    'App',
    'assets',
    'styles',
    'raschFont.legacy.css',
  ),
  '@raschFont.legacy.css': path.resolve(
    process.cwd(),
    'src',
    'common',
    'assets',
    'styles',
    'raschFont.legacy.css',
  ),
  'sections.legacy.css': path.resolve(
    process.cwd(),
    'src',
    app,
    'screens',
    'App',
    'assets',
    'styles',
    'sections.legacy.css',
  ),
  '@sections.legacy.css': path.resolve(
    process.cwd(),
    'src',
    'common',
    'assets',
    'styles',
    'sections.legacy.css',
  ),
  'typography.legacy.css': path.resolve(
    process.cwd(),
    'src',
    app,
    'screens',
    'App',
    'assets',
    'styles',
    'typography.legacy.css',
  ),
  'typography_old.legacy.css': path.resolve(
    // TODO: LEGACY - remove after rebrush
    process.cwd(),
    'src',
    app,
    'screens',
    'App',
    'assets',
    'styles',
    'typography_old.legacy.css',
  ),
  'typographySY.legacy.css': path.resolve(
    process.cwd(),
    'src',
    app,
    'screens',
    'App',
    'assets',
    'styles',
    'typographySY.legacy.css',
  ),
  'variables.legacy.css': path.resolve(
    process.cwd(),
    'src',
    app,
    'screens',
    'App',
    'assets',
    'styles',
    'variables.legacy.css',
  ),
  'gaultMillau.legacy.css': path.resolve(
    process.cwd(),
    'src',
    app,
    'screens',
    'App',
    'assets',
    'styles',
    'gaultMillau.legacy.css',
  ),
  'gmHelpers.legacy.css': path.resolve(
    process.cwd(),
    'src',
    app,
    'screens',
    'App',
    'assets',
    'styles',
    'gmHelpers.legacy.css',
  ),
  '@piano.legacy.css': path.resolve(
    process.cwd(),
    'src',
    'common',
    'assets',
    'styles',
    'piano.legacy.css',
  ),
};
