query PrimaryNavigation {
  navigationPrimaryMenu: menuByName(name: "cash-navigation-hybrid-app") {
    id
    name
    links(limit: 50) {
      edges {
        node {
          id
          link {
            ...MenuLinkFragment
          }
          subtree(limit: 100) {
            edges {
              node {
                id
                link {
                  ...MenuLinkFragment
                }
                subtree(limit: 100) {
                  edges {
                    node {
                      id
                      link {
                        ...MenuLinkFragment
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

fragment MenuLinkFragment on MenuLink {
  label
  description
  path
  routed
  isMainChannel
}
