import {
  WIDGET_AWP_ANALYSER,
  WIDGET_CHART_TIMESERIES,
  WIDGET_CORPORATE_ACTIONS,
  WIDGET_CURRENCY_CALCULATOR,
  WIDGET_DIVIDEND_CALENDAR,
  WIDGET_FULLQUOTE_HEADER,
  WIDGET_INSTRUMENT_ACTIONS,
  WIDGET_INSTRUMENT_GENERIC_DATA,
  WIDGET_INSTRUMENT_HIGH_LOW,
  WIDGET_INSTRUMENT_LATEST_DATA,
  WIDGET_INSTRUMENT_LATEST_DATA_IN_ARTICLE,
  WIDGET_INSTRUMENT_MARKET_PLACES,
  WIDGET_INSTRUMENT_PERFORMANCE,
  WIDGET_MULTIPLE_INSTRUMENTS_GENERIC_DATA,
  WIDGET_MULTIPLE_INSTRUMENTS_GENERIC_DATA_CALLBACK,
  WIDGET_ORDERBOOK,
  WIDGET_QUOTELIST,
  WIDGET_SAVINGS_PLAN_CALCULATOR,
  WIDGET_SECTOR,
  WIDGET_TOP_FLOP,
  WIDGET_TREND_RADAR,
  WIDGET_TREND_RADAR_OVERVIEW,
  WIDGET_VOLUME_TURNOVER,
  WIDGET_WIKIFOLIO,
  WIDGET_FULLQUOTE_HEADER_BNP,
} from './constants';
import { WidgetParagraphProps } from '../Paragraphs/components/WidgetParagraph/typings';

export type WidgetsProps = Partial<WidgetParagraphProps> & {
  component:
    | typeof WIDGET_QUOTELIST
    | typeof WIDGET_AWP_ANALYSER
    | typeof WIDGET_SAVINGS_PLAN_CALCULATOR
    | typeof WIDGET_CURRENCY_CALCULATOR
    | typeof WIDGET_ORDERBOOK
    | typeof WIDGET_INSTRUMENT_ACTIONS
    | typeof WIDGET_INSTRUMENT_LATEST_DATA
    | typeof WIDGET_INSTRUMENT_PERFORMANCE
    | typeof WIDGET_INSTRUMENT_MARKET_PLACES
    | typeof WIDGET_INSTRUMENT_HIGH_LOW
    | typeof WIDGET_CHART_TIMESERIES
    | typeof WIDGET_FULLQUOTE_HEADER
    | typeof WIDGET_VOLUME_TURNOVER
    | typeof WIDGET_SECTOR
    | typeof WIDGET_TREND_RADAR
    | typeof WIDGET_INSTRUMENT_LATEST_DATA_IN_ARTICLE
    | typeof WIDGET_INSTRUMENT_GENERIC_DATA
    | typeof WIDGET_TOP_FLOP
    | typeof WIDGET_CORPORATE_ACTIONS
    | typeof WIDGET_TREND_RADAR_OVERVIEW
    | typeof WIDGET_MULTIPLE_INSTRUMENTS_GENERIC_DATA
    | typeof WIDGET_MULTIPLE_INSTRUMENTS_GENERIC_DATA_CALLBACK
    | typeof WIDGET_WIKIFOLIO
    | typeof WIDGET_FULLQUOTE_HEADER_BNP
    | typeof WIDGET_DIVIDEND_CALENDAR;
};
