/* istanbul ignore file */

import clientFactory from '../../../common/entry/client/factory';
import App from '../../screens/App';
import AutoUpdateProvider from '../../screens/App/components/AutoUpdateProvider';
import RaschProviders from '../../screens/App/components/RaschProviders';
/* @ts-ignore TODO: TS7016 ->  Could not find a declaration file for module '../../../shared/serviceWorker'. '/Users/bhs/code/work/rasch-stack/src/sha */
import { register } from '../../../shared/serviceWorker';
import { displayInfoToast } from '../../screens/App/components/Toast';
import generateApolloCachePolicy from '../../../shared/generateApolloCachePolicy';
import { configureClientStore } from '../../shared/configureStore';

const isPWApp = Boolean(
  (!__TESTING__ &&
    __CLIENT__ &&
    /* @ts-ignore TODO: TS7053 ->  Element implicitly has an 'any' type because expression of type '"standalone"' can't be used to index type 'Navigator'. */
    (global?.navigator?.['standalone'] ||
      window.matchMedia('(display-mode: standalone)').matches)) ||
  false,
);

// Find the DOM node generated by the server
const mountNode: HTMLElement | null = document.getElementById('app') || null;

const preRender = (): void => {
  register({
    /* @ts-ignore TODO: TS7006 ->  Parameter 'registration' implicitly has an 'any' type. */
    /* @ts-ignore TODO: TS7006 ->  Parameter 'callback' implicitly has an 'any' type. */
    onUpdate: (registration, callback) => {
      const registrationWaiting = registration.waiting;
      if (registrationWaiting && isPWApp) {
        displayInfoToast(
          'Eine neue Version ist verfügbar. ',
          'sw-update-toast',
          {
            text: 'Aktualisieren',
            onClick: () => {
              callback(registrationWaiting, {
                type: 'SKIP_WAITING',
              });
            },
          },
        );
      }
    },
  });
};

const client = clientFactory({
  RaschProviders,
  AutoUpdateProvider,
  AppRoutes: App,
  configureClientStore,
  mountNode,
  preRender,
  generateApolloCache: generateApolloCachePolicy,
});

// Run client application.
client();
