export const states: string[] = [
  'Aargau',
  'Appenzell AR',
  'Appenzell IR',
  'Basel Land',
  'Basel Stadt',
  'Bern Land',
  'Bern Stadt',
  'Freiburg',
  'Genf',
  'Glarus',
  'Graubuenden',
  'Jura',
  'Luzern',
  'Neuenburg',
  'Nidwalden',
  'Obwalden',
  'Schaffhausen',
  'Schwyz',
  'Solothurn',
  'St. Gallen Land',
  'St. Gallen Stadt',
  'Tessin',
  'Thurgau',
  'Uri',
  'Waadt',
  'Wallis',
  'Zürich Land',
  'Zürich Stadt',
  'Zug',
  'Liechtenstein',
];
