const fs = require('fs');

const filePath = 'src/shared/@types/autogenerated-gql-types.d.ts';
const autogeneratedTypes = fs.readFileSync(filePath);
let text = autogeneratedTypes.toString();
text = text.replaceAll('RootQuery', 'Query');
text = text.replaceAll('RootMutation', 'Mutation');
fs.writeFileSync(filePath, text);
