import React, { Suspense } from 'react';
import { useSelector } from 'react-redux';
import compose from 'recompose/compose';
import classNames from 'classnames';
import { assembleAkamaiImgUrl } from '../../../../../../../common/components/Picture/helpers';
import { getRestrictedClassName } from '../../../../../../../shared/helpers/withHelmet';
import { formatWealthNumber } from '../../../Ranking/helpers';
import locationStateSelector from '../../../../../../../shared/selectors/locationStateSelector';
import withHelmet from '../../../../../../shared/decorators/withHelmet';
import Link from '../../../../../../../common/components/Link';
import Picture from '../../../../../../../common/components/Picture';
import Breadcrumbs from '../../../../components/Breadcrumbs';
import EditButtons from '../../../../components/EditButtons';
import Helmet from '../../../../components/Helmet';
import Icon from '../../../../components/Icon';
import Paragraphs from '../../../../components/Paragraphs';
import TextParagraph from '../../../../components/Paragraphs/components/TextParagraph';
import RelatedToContent from '../../../../components/RelatedToContent';
import NetWorthChart from '../../../Ranking/components/NetWorthChart';
import { getTitle } from '../Listing';
import { getTop300Data } from '../../../Ranking/components/NetWorthChart/helpers';
import RankingIcon from '../../../Ranking/components/RankingIcon';
import { RESTRICTION_STATUS_PAID } from '../../../../../../../shared/constants/content';
import { STYLE_1X1_660 } from '../../../../../../../shared/constants/images';
import { LANDING_PAGE_TYPE } from '../../../LandingPage/constants';
import {
  PERSON_PAGE_SIZE,
  RANKING_TYPE_RICHEST,
  SCREEN_LABEL,
} from '../../constants';
import grid from '../../../../../../../common/assets/styles/grid.legacy.css';
import styles from './styles.legacy.css';
import { PersonProps } from '../../typings';

type PersonPropsInner = PersonProps;

const PersonDetail = ({ person, location }: PersonPropsInner) => {
  const clientUrl = useSelector(
    /* @ts-ignore TODO: TS2345 ->  Argument of type 'unknown' is not assignable to parameter of type 'Record<string, any>'. */
    (state) => locationStateSelector(state).clientUrl,
  );

  if (!person || !person.name) {
    return null;
  }

  const { chartData, top300List } = getTop300Data(person, null, {
    noDataIfSingleRanking: true,
  });

  /* @ts-ignore TODO: TS2532 ->  Object is possibly 'undefined'. */
  /* @ts-ignore TODO: TS2532 ->  Object is possibly 'undefined'. */
  const lastRowRanking = top300List[top300List.length - 1]?.node;
  const isMoreThanOneRanking = chartData.x.length > 1;

  const heroImage =
    (Array.isArray(person?.heroImageBody) &&
      person?.heroImageBody.length > 0 &&
      // @ts-ignore wrong paragraphInterface typing in autogenerated typings
      person.heroImageBody[0]?.image?.file) ||
    null;

  // hide the image, if the relativeOriginPath contains a fallback image
  const isHeadless =
    (heroImage?.relativeOriginPath &&
      heroImage?.relativeOriginPath.includes('handelszeitung_fallback', 1)) ||
    (heroImage?.relativeOriginPath &&
      heroImage?.relativeOriginPath.includes('beobachter-fallback', 1)) ||
    false;

  const organizationPositions = [];
  const personPositionsEdges =
    (Array.isArray(person?.personPositions?.edges) &&
      /* @ts-ignore TODO: TS2533 ->  Object is possibly 'null' or 'undefined'. */
      person.personPositions.edges.length > 0 &&
      person?.personPositions?.edges) ||
    null;

  const title = `mehr zu: ${person.name}` || 'mehr zu dieser Person';

  const jsonLd = {
    '@context': 'http://schema.org',
    '@type': 'Person',
    name: person?.firstName || '',
    image:
      (heroImage?.relativeOriginPath &&
        assembleAkamaiImgUrl({
          relativeOriginPath: heroImage?.relativeOriginPath,
          width: 350,
          height: 350,
          focalPointX: heroImage?.focalPointX,
          focalPointY: heroImage?.focalPointY,
          clientUrl,
        })) ||
      '',
    brand: {
      '@context': 'http://schema.org',
      '@type': 'Organization',
      name:
        (personPositionsEdges &&
          /* @ts-ignore TODO: TS2531 ->  Object is possibly 'null'. */
          /* @ts-ignore TODO: TS2533 ->  Object is possibly 'null' or 'undefined'. */
          /* @ts-ignore TODO: TS2533 ->  Object is possibly 'null' or 'undefined'. */
          personPositionsEdges.map((item) => item.node.organization.title)) ||
        '',
    },

    jobTitle:
      (personPositionsEdges &&
        /* @ts-ignore TODO: TS2531 ->  Object is possibly 'null'. */
        /* @ts-ignore TODO: TS2533 ->  Object is possibly 'null' or 'undefined'. */
        personPositionsEdges.map((item) => item.node.position)) ||
      '',

    sameAs: person?.moneyhousePreferredUri || '',
    isAccessibleForFree: true,
    hasPart: undefined,
  };

  /* @ts-ignore TODO: TS2345 ->  Argument of type 'Maybe<string> | undefined' is not assignable to parameter of type 'string'. */
  if ([RESTRICTION_STATUS_PAID].includes(person?.restrictionStatus)) {
    jsonLd.isAccessibleForFree = false;

    /* @ts-ignore TODO: TS2322 ->  Type '{ '@type' */
    jsonLd.hasPart = [
      {
        '@type': 'WebPageElement',
        isAccessibleForFree: 'False',
        cssSelector: `.${getRestrictedClassName(person?.__typename)}`,
      },
      {
        '@type': 'WebPageElement',
        isAccessibleForFree: 'False',
        cssSelector: '.paywall-person-text',
      },
      {
        '@type': 'WebPageElement',
        isAccessibleForFree: 'False',
        cssSelector: '.paywall-person-paragraphs',
      },
      {
        '@type': 'WebPageElement',
        isAccessibleForFree: 'False',
        cssSelector: '.paywall-person-listing',
      },
    ];
  }

  const script = [
    {
      type: 'application/ld+json',
      innerHTML: JSON.stringify(jsonLd),
    },
  ];

  if (personPositionsEdges) {
    for (let i = 0; i < personPositionsEdges.length; ++i) {
      organizationPositions.push(
        /* @ts-ignore TODO: TS2531 ->  Object is possibly 'null'. */
        personPositionsEdges[i].node?.organization?.organizationPositions,
      );
    }
  }

  return (
    <div className={classNames(SCREEN_LABEL, styles.Wrapper)}>
      <EditButtons
        /* @ts-ignore TODO: TS2322 ->  Type 'Maybe<string> | undefined' is not assignable to type 'string'. */
        editContentUri={person.editContentUri}
        /* @ts-ignore TODO: TS2322 ->  Type 'Maybe<string> | undefined' is not assignable to type 'string | undefined'. */
        editRelationUri={person.editRelationUri}
        /* @ts-ignore TODO: TS2322 ->  Type 'Maybe<string> | undefined' is not assignable to type 'string | undefined'. */
        cloneContentUri={person.cloneContentUri}
      />
      <Helmet script={(person?.moneyhousePreferredUri && script) || []} />
      <div className={styles.HeaderWrapper}>
        <div className={grid.Container}>
          <Breadcrumbs
            /* @ts-ignore TODO: TS2322 ->  Type 'Maybe<string> | undefined' is not assignable to type 'string | undefined'. */
            pageUrl={person.preferredUri}
            /* @ts-ignore TODO: TS2322 ->  Type 'Maybe<ActiveMenuTrailItemConnection> | undefined' is not assignable to type 'BreadcrumbsItems | undefined'. */
            items={person.activeMenuTrail}
          />
          <div className={grid.Row}>
            <div
              className={classNames(
                grid.ColXs24,
                grid.ColOffsetMd2,
                grid.ColMd20,
              )}
            >
              <h1 className={styles.Title}>{getTitle(RANKING_TYPE_RICHEST)}</h1>
              <div className={styles.BackWrapper}>
                <Link
                  className={styles.BackLink}
                  path={`/bilanz/die-300-reichsten-${
                    (lastRowRanking?.ranking?.year &&
                      `${lastRowRanking?.ranking?.year}`) ||
                    ''
                  }`}
                >
                  <Icon type="IconChevronLeft" /> Zurück zur Liste
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className={grid.Container}>
        <div className={grid.Row}>
          <div
            className={classNames(
              grid.ColXs24,
              grid.ColOffsetMd2,
              grid.ColMd20,
            )}
          >
            <div className={grid.Row}>
              <div className={classNames(grid.ColXs24, grid.ColSm10)}>
                {!isHeadless && heroImage?.relativeOriginPath && (
                  <Picture
                    relativeOrigin={heroImage?.relativeOriginPath}
                    focalPointX={heroImage?.focalPointX}
                    focalPointY={heroImage?.focalPointY}
                    className={styles.Image}
                    alt={heroImage?.alt || ''}
                    style_320={STYLE_1X1_660}
                  />
                )}
                <div className={styles.PersonTitle}>{person.name}</div>
                <p className={styles.ListTitle}>
                  Vermögen
                  {(lastRowRanking?.ranking?.year &&
                    ` im Jahr ${lastRowRanking?.ranking?.year}`) ||
                    ''}
                </p>
                <div className={styles.RankingValue}>
                  {formatWealthNumber(lastRowRanking?.rankingValue)}
                  {lastRowRanking?.rankingTrend !== 'new' &&
                    lastRowRanking?.rankingTrend !== 'returnee' && (
                      <RankingIcon
                        /* @ts-ignore TODO: TS2322 ->  Type '{ Positive */
                        addStyles={{
                          Positive: styles.Positive,
                          Negative: styles.Negative,
                          RankingIcon: styles.RankingIcon,
                        }}
                        rankingTrend={lastRowRanking?.rankingTrend}
                      />
                    )}
                </div>
                <div>
                  <div className={styles.List}>
                    <div>
                      <p className={styles.ListTitle}>Rang</p>
                      <p className={styles.ListItem}>
                        {lastRowRanking?.rankingPosition || <>&ndash;</>}
                        {(lastRowRanking?.rankingTrend === 'new' ||
                          lastRowRanking?.rankingTrend === 'returnee') && (
                          <RankingIcon
                            /* @ts-ignore TODO: TS2322 ->  Type '{ readonly Wrapper */
                            addStyles={styles}
                            rankingTrend={lastRowRanking?.rankingTrend}
                          />
                        )}
                      </p>
                    </div>
                    <div>
                      <p className={styles.ListTitle}>Branche</p>
                      <p className={styles.ListItem}>
                        {lastRowRanking?.rankingIndustry || <>&ndash;</>}
                      </p>
                    </div>
                  </div>
                </div>
                <div className={styles.StateWrapper}>
                  <p className={styles.ListTitle}>Kanton</p>
                  <p className={styles.ListItem}>
                    {lastRowRanking?.rankingState || <>&ndash;</>}
                  </p>
                </div>
              </div>
              <div
                className={classNames(
                  grid.ColXs24,
                  grid.ColOffsetMd1,
                  grid.ColSm14,
                  grid.ColMd13,
                )}
              >
                <div className={classNames('paywall-person-paragraphs')}>
                  {typeof person.text !== 'undefined' && (
                    <div className={styles.TextWrapper}>
                      <TextParagraph
                        addClass={classNames('paywall-person-text')}
                        textParagraph={{ text: person.text }}
                      />
                    </div>
                  )}
                  <Suspense>
                    {isMoreThanOneRanking && (
                      <NetWorthChart
                        x={chartData.x}
                        y={chartData.y}
                        /* @ts-ignore TODO: TS2322 ->  Type 'string' is not assignable to type 'null | undefined'. */
                        addClass={styles.Chart}
                      />
                    )}
                  </Suspense>
                  <Paragraphs
                    pageBody={person.content}
                    colStyle={grid.ColXs24}
                    origin={LANDING_PAGE_TYPE}
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <RelatedToContent
        title={person.name}
        relatedToTitle={title}
        location={location}
      />
    </div>
  );
};

const PersonWrapper = compose<any, any>(
  withHelmet({
    /* @ts-ignore TODO: TS7006 ->  Parameter 'mapProps' implicitly has an 'any' type. */
    getNode: (mapProps) => mapProps.person || null,
    /* @ts-ignore TODO: TS7006 ->  Parameter 'mapProps' implicitly has an 'any' type. */
    getNodesCount: (mapProps) => mapProps.person?.personArticles?.count || 0,
    pageSize: PERSON_PAGE_SIZE,
  }),
)(PersonDetail);

export default PersonWrapper;
