query PrimaryNavigation @api(name: cms) {
  navigationPrimaryMenu: menuByName(name: "beo-navigation-primary") {
    id
    name
    links(limit: 100) {
      edges {
        node {
          id
          link {
            ...MenuLinkFragment
          }
          subtree(limit: 100) {
            edges {
              node {
                id
                link {
                  ...MenuLinkFragment
                }
                subtree(limit: 100) {
                  edges {
                    node {
                      id
                      link {
                        ...MenuLinkFragment
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  navigationSecondaryMenu: menuByName(name: "beo-navigation-secondary") {
    id
    name
    links(limit: 100) {
      edges {
        node {
          id
          link {
            ...MenuLinkFragment
          }
          subtree(limit: 100) {
            edges {
              node {
                id
                link {
                  ...MenuLinkFragment
                }
              }
            }
          }
        }
      }
    }
  }
  navigationQuickAccessMenu: menuByName(name: "beo-navigation-quickaccess") {
    id
    name
    links(limit: 100) {
      edges {
        node {
          id
          link {
            ...MenuLinkFragment
          }
        }
      }
    }
  }
}

fragment MenuLinkFragment on MenuLink {
  label
  description
  path
  routed
  expanded
}
